Repository aurora-munge/databasteknik, pull requests merged in 2018-04, with the labels that each got.

#78 Moved plusButton to left side of amount.
  htdocs/css/style.css
  view/cart/cart.php
Labels: Design fix

#79 Refactoring
  config/di.php
  htdocs/css/style.css
  sql/uber.sql
  src/Admin/AdminController.php
  src/Base/BaseController.php
  src/Category/CategoryController.php
  src/Cookie/CookieController.php
  src/Order/OrderController.php
  src/Product/ProductController.php
  src/User/UserController.php
  view/admin/admin.php
  view/admin/order.php
  view/admin/users.php
  view/order/order.php
Labels: Design fix, bug fix

#81 Coupon system added
  config/route/cart.php
  src/Cart/CartController.php
  src/Coupon/Coupon.php
  src/Order/OrderController.php
  view/cart/checkout.php
  view/defaults/footer.php
Labels: enhancement, help wanted

#85 "Add coupon" functionality
  config/route/admin.php
  htdocs/css/style.css
  src/Admin/AdminController.php
  src/Admin/HTMLForm/CouponCreateForm.php
  view/admin/admin.php
Labels: enhancement

#86 Changed design on navbar to be more clean.
  src/Navbar/Navbar.php
Labels: Design fix, validation

#87 Company Management
  .gitignore
  config/di.php
  config/route.php
  config/route/cm.php
  src/Admin/AdminController.php
  src/Cart/CartController.php
  src/Management/ManagementController.php
  src/Order/OrderItem.php
  src/Order/Orders.php
  view/defaults/footer.php
  view/management/bestselling.php
  view/management/management.php
  view/management/mostbought.php
  view/management/profit.php
Labels: enhancement, validation

#88 Fixed search. You can now search using åäö.
  src/Product/Product.php
Labels: bug fix

#90 Valdiation fixes
  composer.lock
  sql/uber.sql
  src/Admin/HTMLForm/CouponCreateForm.php
  src/Coupon/Coupon.php
  src/Database/ActiveRecordModel.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/HTMLForm/UserUpdateForm.php
Labels: Composer update, bug fix, validation

#91 Fixes for various validation fixes.
  config/di.php
  config/error_reporting.php
  config/route/internal.php
  src/Admin/AdminController.php
  src/Admin/HTMLForm/AdminBuyFemaleForm.php
  src/Admin/HTMLForm/AdminBuyMaleForm.php
  src/Admin/HTMLForm/AdminUpdateProductForm.php
  src/Admin/HTMLForm/CouponCreateForm.php
  src/Ajax/AjaxController.php
  src/Base/Base.php
  src/Base/BaseController.php
  src/Cart/CartController.php
  src/Category/Category.php
  src/Category/CategoryController.php
  src/Coupon/Coupon.php
  src/Database/ActiveRecordModel.php
  src/Management/ManagementController.php
  src/Navbar/Navbar.php
  src/Order/OrderController.php
  src/Order/OrderItem.php
  src/Order/Orders.php
  src/Page/PageRender.php
  src/Product/Product.php
  src/Product/ProductController.php
  src/Search/SearchController.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/HTMLForm/UserUpdateForm.php
  src/User/User.php
  src/User/UserController.php
  view/admin/order.php
  view/base/about.php
  view/base/home.php
  view/cart/cart.php
  view/cart/checkout.php
  view/cart/order.php
  view/category/categories.php
  view/category/specificCategory.php
  view/order/order.php
  view/product/product.php
  view/product/under500.php
Labels: bug fix, validation

#95 Issue fixing.
  config/route/product.php
  src/Category/CategoryController.php
  src/Management/ManagementController.php
  src/Product/ProductController.php
  view/base/home.php
  view/management/bestselling.php
  view/product/under500Female.php
  view/product/under500Male.php
Labels: Design fix, bug fix, validation

#96 Pagination
  .scrutinizer.yml
  composer.json
  composer.lock
  config.neon
  src/Admin/AdminController.php
  src/Admin/HTMLForm/AdminBuyFemaleForm.php
  src/Admin/HTMLForm/AdminBuyMaleForm.php
  src/Admin/HTMLForm/AdminUpdateProductForm.php
  src/Admin/HTMLForm/CouponCreateForm.php
  src/Ajax/AjaxController.php
  src/Base/BaseController.php
  src/Cart/CartController.php
  src/Category/CategoryController.php
  src/Coupon/Coupon.php
  src/Management/ManagementController.php
  src/Order/OrderController.php
  src/Order/OrderItem.php
  src/Order/Orders.php
  src/Product/Product.php
  src/Product/ProductController.php
  src/Search/SearchController.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/HTMLForm/UserUpdateForm.php
  src/User/User.php
  src/User/UserController.php
  view/admin/admin.php
  view/admin/low.php
  view/admin/products.php
  view/admin/users.php
  view/base/home.php
  view/category/specificCategory.php
  view/product/products.php
  view/product/under500Female.php
  view/product/under500Male.php
Labels: bug fix, enhancement, validation

#97 Added start and end for pagination
  view/admin/low.php
  view/admin/products.php
  view/product/products.php
  view/product/under500Female.php
  view/product/under500Male.php
Labels: Design fix, enhancement

#100 Fixing bugs and refactoring
  README.md
  src/Admin/AdminController.php
  src/Ajax/AjaxController.php
  src/Base/Base.php
  src/Base/BaseController.php
  src/Management/Management.php
  src/Management/ManagementController.php
  src/Order/OrderController.php
  src/Product/ProductController.php
  src/Search/SearchController.php
  src/User/UserController.php
  view/admin/low.php
  view/admin/products.php
  view/product/products.php
  view/product/under500Female.php
  view/product/under500Male.php
Labels: bug fix, validation

#101 Updates to Coupon handling
  config/route/ajax.php
  htdocs/js/cart.js
  src/Ajax/AjaxController.php
  src/Cart/CartController.php
  src/Coupon/Coupon.php
  src/Order/OrderController.php
  view/cart/checkout.php
  view/cart/order.php
  view/order/order.php
Labels: bug fix, enhancement

#102 Moved pagination and display to own classes.
  config/di.php
  src/Admin/AdminController.php
  src/Cart/CartController.php
  src/Category/CategoryController.php
  src/Management/ManagementController.php
  src/Order/OrderController.php
  src/Pagination/Pagination.php
  src/Product/ProductController.php
  src/Render/Render.php
  src/User/UserController.php
Labels: validation
