Repository aurora-munge/databasteknik, pull requests merged in 2018-03, with the labels that each got.

#27 Updated design on various places
  htdocs/css/style.css
  src/Navbar/Navbar.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  view/product/product.php
Labels: enhancement

#28 Updated so that you can reach profile via navbar when you're logged in.
  config/navbar.php
  src/Navbar/Navbar.php
Labels: bug fix

#30 Fixed categories.
  sql/data.sql
  sql/tables.sql
  src/Category/Category.php
  src/Category/CategoryController.php
  view/category/categories.php
Labels: enhancement

#31 Profile Page and random fixes
  htdocs/css/style.css
  src/Navbar/Navbar.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/User.php
  view/user/profile.php
Labels: bug fix, enhancement

#34 Bootstrap for local development
  composer.json
  composer.lock
  src/Page/PageRender.php
  view/defaults/layout.php
Labels: enhancement

#33 Category design.
  src/Category/Category.php
  src/Category/CategoryController.php
  view/category/categories.php
Labels: bug fix, enhancement

#37 Abillity to add local scripts.
  src/Page/PageRender.php
  view/defaults/layout.php
Labels: enhancement

#38 Dummy data script
  sql/dummy.sh
  sql/dummy.txt
Labels: enhancement

#40 Updated dummy data script.
  sql/dummy.sh
  sql/dummy.txt
Labels: bug fix

#41 Products
  .gitignore
  composer.json
  composer.lock
  config/route/product.php
  sql/dummy.sh
  src/Category/Category.php
  src/Product/ProductController.php
  view/category/categories.php
  view/product/products.php
Labels: bug fix, enhancement

#42 Subcategories added
  sql/dummy.sh
  sql/sub_categories.sql
  sql/uber.sql
  src/Category/Category.php
  src/Category/CategoryController.php
  view/category/categories.php
  view/category/specificCategory.php
  view/product/products.php
Labels: bug fix, enhancement

#44 Fixed navigation
  config/navbar.php
  src/Navbar/Navbar.php
  src/Page/PageRender.php
  view/cart/cart.php
Labels: bug fix, enhancement

#48 Fixed issues.
  src/Navbar/Navbar.php
  view/cart/cart.php
  view/product/product.php
Labels: bug fix, enhancement

#49 Small fixes.
  config/navbar.php
  src/Navbar/Navbar.php
  view/cart/cart.php
Labels: bug fix, enhancement

#50 Can now edit profile
  .gitattributes
  config/route/user.php
  src/User/HTMLForm/UserUpdateForm.php
  src/User/User.php
  src/User/UserController.php
  view/user/profile.php
Labels: enhancement

#53 Added "Back" button to subcategory view and product list.
  htdocs/css/style.css
  src/Category/CategoryController.php
  src/Product/ProductController.php
  view/category/specificCategory.php
  view/category/specificSubCategory.php
  view/product/products.php
Labels: enhancement

#57 Updated order details.
  src/Order/OrderController.php
  src/Product/Product.php
  view/order/order.php
Labels: bug fix, enhancement

#58 Fixed product amount.
  src/Cart/CartController.php
  src/Product/Product.php
Labels: bug fix

#59 Fixed issues and more.
  composer.json
  composer.lock
  htdocs/css/style.css
  htdocs/js/product.js
  src/Navbar/Navbar.php
  src/Page/PageRender.php
  view/defaults/layout.php
  view/product/product.php
Labels: bug fix, enhancement

#61 Top10 and more.
  config/route/category.php
  config/route/product.php
  sql/dummy.sh
  sql/tables.sql
  sql/uber.sql
  src/Base/BaseController.php
  src/Database/ActiveRecordModel.php
  src/Order/OrderItem.php
  src/Product/Product.php
  src/Product/ProductController.php
  view/base/home.php
  view/category/specificCategory.php
Labels: bug fix, enhancement, validation

#62 Design fixes
  composer.lock
  src/Order/OrderItem.php
  view/base/home.php
  view/cart/cart.php
  view/cart/checkout.php
  view/cart/order.php
  view/order/order.php
  view/order/orders.php
Labels: bug fix, enhancement

#64 Added abillity to search for products.
  config/di.php
  config/route.php
  config/route/search.php
  src/Navbar/Navbar.php
  src/Product/Product.php
  src/Search/SearchController.php
  view/search/search.php
Labels: enhancement

#65 Added abillity to remove products from cart.
  config/di.php
  config/route/ajax.php
  htdocs/css/style.css
  htdocs/js/cart.js
  htdocs/js/product.js
  src/Ajax/AjaxController.php
  src/Page/PageRender.php
  view/cart/cart.php
Labels: enhancement

#66 Added button that will remove all products from cart.
  config/route/ajax.php
  htdocs/js/cart.js
  src/Ajax/AjaxController.php
  view/cart/cart.php
Labels: enhancement

#70 Updated image on productview
  htdocs/img/car.png
  htdocs/img/shirt.png
  view/product/product.php
Labels: bug fix

#71 Fixed design, fixed buttons
  htdocs/css/style.css
  src/User/HTMLForm/UserUpdateForm.php
  view/category/categories.php
  view/category/specificCategory.php
  view/order/order.php
  view/order/orders.php
  view/product/products.php
  view/user/profile.php
Labels: bug fix, enhancement

#72 Aurora scrutinizer
  src/Ajax/AjaxController.php
  src/Category/Category.php
  src/Cookie/CookieController.php
  src/Navbar/Navbar.php
  src/Order/OrderController.php
  src/Order/OrderItem.php
  src/Search/SearchController.php
  view/cart/cart.php
  view/search/search.php
Labels: bug fix, validation

#73 Products under 500kr.
  config/route/product.php
  htdocs/css/style.css
  htdocs/js/cart.js
  sql/dummy.sh
  src/Base/BaseController.php
  src/Product/Product.php
  src/Product/ProductController.php
  view/base/home.php
  view/product/product.php
  view/product/under500.php
Labels: bug fix, enhancement
