Repository aurora-munge/databasteknik, pull requests merged in 2018-02, with the labels that each got.

#5 Fixed rendering.
  composer.json
  config/di.php
  config/navbar.php
  config/route/base.php
  config/url.php
  htdocs/.htaccess
  htdocs/.htaccess_anax
  htdocs/.htaccess_wwwstudent
  src/App/App.php
  src/Base/Base.php
  src/Base/BaseController.php
  src/Navbar/Navbar.php
  src/Page/PageRender.php
  view/base/about.php
  view/base/home.php
  view/defaults/footer.php
  view/defaults/header.php
  view/defaults/layout.php
  view/navbar/navbar.php
Labels: enhancement

#9 Updated SQL
  README.md
  sql/data.sql
  sql/tables.sql
Labels: enhancement

#10 Fixed codacy problems.
  config/di.php
  src/Category/CategoryController.php
  src/Product/ProductController.php
  view/category/specificCategory.php
  view/product/product.php
Labels: validation

#11 Implementeted bootstrap
  config/database_example.php
  view/defaults/layout.php
Labels: enhancement

#12 Added Product class and a simple view
  src/Database/DatabaseConfigure.php
  src/Product/Product.php
  src/Product/ProductController.php
  view/product/product.php
Labels: enhancement

#13 Added user support.
  config/di.php
  config/navbar.php
  config/route.php
  config/route/user.php
  sql/data.sql
  sql/tables.sql
  src/HTMLForm/Form.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/User.php
  src/User/UserController.php
Labels: enhancement

#16 Added create new user page, login and profilepage
  config/route/user.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/User.php
  src/User/UserController.php
  view/user/profile.php
Labels: enhancement

#19 Fixed bugs and issues.
  config/di.php
  config/route/internal.php
  config/session.php
  config/url.php
  config/view.php
  htdocs/cimage/img.php
  htdocs/index.php
  src/User/HTMLForm/UserCreateForm.php
  src/User/HTMLForm/UserLoginForm.php
  src/User/User.php
Labels: bug fix, validation

#20 Fixed more issues.
  htdocs/cimage/img.php
  src/User/HTMLForm/UserCreateForm.php
  view/user/profile.php
Labels: validation

#21 Session
  .scrutinizer.yml
  config/route/user.php
  src/User/UserController.php
  view/user/profile.php
Labels: enhancement
